name: Create release

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: "ðŸš€ Release"
    runs-on: ubuntu-latest
    steps:
      - name: "Check-out"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Update Release CHANGELOG"
        id: update-release-changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          onlyLastTag: true
          stripHeaders: false
          base: "CHANGELOG.md"
          headerLabel: "# Changelog"
          breakingLabel: '### Breaking'
          enhancementLabel: '### Enhancements'
          stripGeneratorNotice: true
          bugsLabel: '### Fixes'
          issues: false
          issuesWoLabels: false
          pullRequests: true
          prWoLabels: true
          author: false
          verbose: true
      - name: Commit CHANGELOG Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git diff --cached --quiet || git commit -m "Update CHANGELOG for version ${GITHUB_REF#refs/tags/}"
      - name: Push CHANGELOG changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: false
      - name: "ðŸš€ Create GitHub Release"
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true
          append_body: true
          body: |

            ---
            **Note**: After this GitHub release is created, the Maven Central deployment must be manually released at https://central.sonatype.com/publishing/deployments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
